version: '3'

services:
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stackathon
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "9999:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes: 
      - "~/pgadmin:/var/lib/pgadmin"
  api:
    build: ./api
    environment:
      DB_USER: dev
      DB_PASSWORD: password
      DB_NAME: stackathon
      DB_PORT: 5432
      DB_HOST: db
      API_PORT: 8080
      API_VERSION: v1
    ports:
      - "7777:8080"
    depends_on: 
      - db
  client:
    build: ./client
    environment:
      API_NAME: api
      API_PORT: 8080
    ports:
      - "8888:80"
    depends_on:
      - db
      - api
